name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - os: ubuntu-latest
            rust: stable
            artifact_name: microserver
            asset_name: microserver_linux.zip
          - os: macOS-latest
            rust: stable
            artifact_name: microserver
            asset_name: microserver_osx.zip
          - os: windows-latest
            rust: stable
            artifact_name: microserver.exe
            asset_name: microserver_windows.zip
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@master
        with:
          rust-version: stable
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the crate for release
        run: |
          cargo build --release
          ls -la target/release
      - name: Apply upx
        uses: svenstaro/upx-action@v1-release
        with:
          file: target/release/${{ matrix.artifact_name }}
      - name: Zip the artifact
        shell: bash
        run: |
          echo "Setting exec permissions"
          chmod +x ./target/release/${{ matrix.artifact_name }}
          echo "Zipping"
          if [[ "${{matrix.os}}" == "macOS-latest" ]]
          then
            zip ${{matrix.asset_name}} target/release/${{matrix.artifact_name}}
          else
            7z a ${{matrix.asset_name}} target/release/${{matrix.artifact_name}}
          fi
      - name: Upload binaries to GitHub release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}

  crates:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@master
        with:
          rust-version: stable
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish to crates.io
        run: |
          cargo login ${{secrets.crates_key}}
          cargo publish
